//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// 此源代码由 wsdl 自动生成, Version=4.0.30319.33440。
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback SaveInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetInfoStringTypeXMLOperationCompleted;
    
    private System.Threading.SendOrPostCallback SaveInfoStringTypeXMLOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetInfoForJavaOperationCompleted;
    
    private System.Threading.SendOrPostCallback SaveInfoForJavaOperationCompleted;
    
    /// <remarks/>
    public WebService() {
        this.Url = "http://10.10.2.109:9000/WebService.asmx";
    }
    
    /// <remarks/>
    public event GetInfoCompletedEventHandler GetInfoCompleted;
    
    /// <remarks/>
    public event SaveInfoCompletedEventHandler SaveInfoCompleted;
    
    /// <remarks/>
    public event HelloWorldCompletedEventHandler HelloWorldCompleted;
    
    /// <remarks/>
    public event GetInfoStringTypeXMLCompletedEventHandler GetInfoStringTypeXMLCompleted;
    
    /// <remarks/>
    public event SaveInfoStringTypeXMLCompletedEventHandler SaveInfoStringTypeXMLCompleted;
    
    /// <remarks/>
    public event GetInfoForJavaCompletedEventHandler GetInfoForJavaCompleted;
    
    /// <remarks/>
    public event SaveInfoForJavaCompletedEventHandler SaveInfoForJavaCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] GetInfo(string organizationid, string RegistrationCode, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] stream) {
        object[] results = this.Invoke("GetInfo", new object[] {
                    organizationid,
                    RegistrationCode,
                    stream});
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetInfo(string organizationid, string RegistrationCode, byte[] stream, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetInfo", new object[] {
                    organizationid,
                    RegistrationCode,
                    stream}, callback, asyncState);
    }
    
    /// <remarks/>
    public byte[] EndGetInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public void GetInfoAsync(string organizationid, string RegistrationCode, byte[] stream) {
        this.GetInfoAsync(organizationid, RegistrationCode, stream, null);
    }
    
    /// <remarks/>
    public void GetInfoAsync(string organizationid, string RegistrationCode, byte[] stream, object userState) {
        if ((this.GetInfoOperationCompleted == null)) {
            this.GetInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInfoOperationCompleted);
        }
        this.InvokeAsync("GetInfo", new object[] {
                    organizationid,
                    RegistrationCode,
                    stream}, this.GetInfoOperationCompleted, userState);
    }
    
    private void OnGetInfoOperationCompleted(object arg) {
        if ((this.GetInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetInfoCompleted(this, new GetInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] SaveInfo(string organizationid, string RegistrationCode, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] stream) {
        object[] results = this.Invoke("SaveInfo", new object[] {
                    organizationid,
                    RegistrationCode,
                    stream});
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSaveInfo(string organizationid, string RegistrationCode, byte[] stream, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SaveInfo", new object[] {
                    organizationid,
                    RegistrationCode,
                    stream}, callback, asyncState);
    }
    
    /// <remarks/>
    public byte[] EndSaveInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public void SaveInfoAsync(string organizationid, string RegistrationCode, byte[] stream) {
        this.SaveInfoAsync(organizationid, RegistrationCode, stream, null);
    }
    
    /// <remarks/>
    public void SaveInfoAsync(string organizationid, string RegistrationCode, byte[] stream, object userState) {
        if ((this.SaveInfoOperationCompleted == null)) {
            this.SaveInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveInfoOperationCompleted);
        }
        this.InvokeAsync("SaveInfo", new object[] {
                    organizationid,
                    RegistrationCode,
                    stream}, this.SaveInfoOperationCompleted, userState);
    }
    
    private void OnSaveInfoOperationCompleted(object arg) {
        if ((this.SaveInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SaveInfoCompleted(this, new SaveInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] HelloWorld([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] byteArray) {
        object[] results = this.Invoke("HelloWorld", new object[] {
                    byteArray});
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginHelloWorld(byte[] byteArray, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("HelloWorld", new object[] {
                    byteArray}, callback, asyncState);
    }
    
    /// <remarks/>
    public byte[] EndHelloWorld(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public void HelloWorldAsync(byte[] byteArray) {
        this.HelloWorldAsync(byteArray, null);
    }
    
    /// <remarks/>
    public void HelloWorldAsync(byte[] byteArray, object userState) {
        if ((this.HelloWorldOperationCompleted == null)) {
            this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
        }
        this.InvokeAsync("HelloWorld", new object[] {
                    byteArray}, this.HelloWorldOperationCompleted, userState);
    }
    
    private void OnHelloWorldOperationCompleted(object arg) {
        if ((this.HelloWorldCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInfoStringTypeXML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string GetInfoStringTypeXML(string organizationid, string RegistrationCode, string xmlstr) {
        object[] results = this.Invoke("GetInfoStringTypeXML", new object[] {
                    organizationid,
                    RegistrationCode,
                    xmlstr});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetInfoStringTypeXML(string organizationid, string RegistrationCode, string xmlstr, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetInfoStringTypeXML", new object[] {
                    organizationid,
                    RegistrationCode,
                    xmlstr}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndGetInfoStringTypeXML(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void GetInfoStringTypeXMLAsync(string organizationid, string RegistrationCode, string xmlstr) {
        this.GetInfoStringTypeXMLAsync(organizationid, RegistrationCode, xmlstr, null);
    }
    
    /// <remarks/>
    public void GetInfoStringTypeXMLAsync(string organizationid, string RegistrationCode, string xmlstr, object userState) {
        if ((this.GetInfoStringTypeXMLOperationCompleted == null)) {
            this.GetInfoStringTypeXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInfoStringTypeXMLOperationCompleted);
        }
        this.InvokeAsync("GetInfoStringTypeXML", new object[] {
                    organizationid,
                    RegistrationCode,
                    xmlstr}, this.GetInfoStringTypeXMLOperationCompleted, userState);
    }
    
    private void OnGetInfoStringTypeXMLOperationCompleted(object arg) {
        if ((this.GetInfoStringTypeXMLCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetInfoStringTypeXMLCompleted(this, new GetInfoStringTypeXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveInfoStringTypeXML", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string SaveInfoStringTypeXML(string organizationid, string RegistrationCode, string xmlstr) {
        object[] results = this.Invoke("SaveInfoStringTypeXML", new object[] {
                    organizationid,
                    RegistrationCode,
                    xmlstr});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSaveInfoStringTypeXML(string organizationid, string RegistrationCode, string xmlstr, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SaveInfoStringTypeXML", new object[] {
                    organizationid,
                    RegistrationCode,
                    xmlstr}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndSaveInfoStringTypeXML(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void SaveInfoStringTypeXMLAsync(string organizationid, string RegistrationCode, string xmlstr) {
        this.SaveInfoStringTypeXMLAsync(organizationid, RegistrationCode, xmlstr, null);
    }
    
    /// <remarks/>
    public void SaveInfoStringTypeXMLAsync(string organizationid, string RegistrationCode, string xmlstr, object userState) {
        if ((this.SaveInfoStringTypeXMLOperationCompleted == null)) {
            this.SaveInfoStringTypeXMLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveInfoStringTypeXMLOperationCompleted);
        }
        this.InvokeAsync("SaveInfoStringTypeXML", new object[] {
                    organizationid,
                    RegistrationCode,
                    xmlstr}, this.SaveInfoStringTypeXMLOperationCompleted, userState);
    }
    
    private void OnSaveInfoStringTypeXMLOperationCompleted(object arg) {
        if ((this.SaveInfoStringTypeXMLCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SaveInfoStringTypeXMLCompleted(this, new SaveInfoStringTypeXMLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetInfoForJava", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] GetInfoForJava(string organizationid, string RegistrationCode, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] stream) {
        object[] results = this.Invoke("GetInfoForJava", new object[] {
                    organizationid,
                    RegistrationCode,
                    stream});
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetInfoForJava(string organizationid, string RegistrationCode, byte[] stream, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetInfoForJava", new object[] {
                    organizationid,
                    RegistrationCode,
                    stream}, callback, asyncState);
    }
    
    /// <remarks/>
    public byte[] EndGetInfoForJava(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public void GetInfoForJavaAsync(string organizationid, string RegistrationCode, byte[] stream) {
        this.GetInfoForJavaAsync(organizationid, RegistrationCode, stream, null);
    }
    
    /// <remarks/>
    public void GetInfoForJavaAsync(string organizationid, string RegistrationCode, byte[] stream, object userState) {
        if ((this.GetInfoForJavaOperationCompleted == null)) {
            this.GetInfoForJavaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInfoForJavaOperationCompleted);
        }
        this.InvokeAsync("GetInfoForJava", new object[] {
                    organizationid,
                    RegistrationCode,
                    stream}, this.GetInfoForJavaOperationCompleted, userState);
    }
    
    private void OnGetInfoForJavaOperationCompleted(object arg) {
        if ((this.GetInfoForJavaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetInfoForJavaCompleted(this, new GetInfoForJavaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveInfoForJava", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
    public byte[] SaveInfoForJava(string organizationid, string RegistrationCode, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] stream) {
        object[] results = this.Invoke("SaveInfoForJava", new object[] {
                    organizationid,
                    RegistrationCode,
                    stream});
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSaveInfoForJava(string organizationid, string RegistrationCode, byte[] stream, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SaveInfoForJava", new object[] {
                    organizationid,
                    RegistrationCode,
                    stream}, callback, asyncState);
    }
    
    /// <remarks/>
    public byte[] EndSaveInfoForJava(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((byte[])(results[0]));
    }
    
    /// <remarks/>
    public void SaveInfoForJavaAsync(string organizationid, string RegistrationCode, byte[] stream) {
        this.SaveInfoForJavaAsync(organizationid, RegistrationCode, stream, null);
    }
    
    /// <remarks/>
    public void SaveInfoForJavaAsync(string organizationid, string RegistrationCode, byte[] stream, object userState) {
        if ((this.SaveInfoForJavaOperationCompleted == null)) {
            this.SaveInfoForJavaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveInfoForJavaOperationCompleted);
        }
        this.InvokeAsync("SaveInfoForJava", new object[] {
                    organizationid,
                    RegistrationCode,
                    stream}, this.SaveInfoForJavaOperationCompleted, userState);
    }
    
    private void OnSaveInfoForJavaOperationCompleted(object arg) {
        if ((this.SaveInfoForJavaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.SaveInfoForJavaCompleted(this, new SaveInfoForJavaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void GetInfoCompletedEventHandler(object sender, GetInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public byte[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((byte[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void SaveInfoCompletedEventHandler(object sender, SaveInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SaveInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SaveInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public byte[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((byte[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public byte[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((byte[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void GetInfoStringTypeXMLCompletedEventHandler(object sender, GetInfoStringTypeXMLCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetInfoStringTypeXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetInfoStringTypeXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void SaveInfoStringTypeXMLCompletedEventHandler(object sender, SaveInfoStringTypeXMLCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SaveInfoStringTypeXMLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SaveInfoStringTypeXMLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void GetInfoForJavaCompletedEventHandler(object sender, GetInfoForJavaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetInfoForJavaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetInfoForJavaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public byte[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((byte[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void SaveInfoForJavaCompletedEventHandler(object sender, SaveInfoForJavaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class SaveInfoForJavaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal SaveInfoForJavaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public byte[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((byte[])(this.results[0]));
        }
    }
}
